---
- name: configuring config | Derive configuring host type
  ansible.builtin.set_fact:
    cloudflared_facts_config_host_type: >-
      {{
        'docker'
        if cloudflared_installation_mode == 'docker'
        else 'windows'
        if ansible_facts["os_family"] == "Windows"
        else 'openwrt'
        if ansible_facts["os_family"] == "OpenWrt"
        else 'unix'
      }}

- name: configuring config | Route config file handling by host type
  ansible.builtin.include_tasks: "configuring_config_{{ cloudflared_facts_config_host_type }}.yml"
