---
- name: configuring config windows | Ensure config file parent directory exists
  become: "{{ cloudflared_config_file_become }}"
  ansible.windows.win_file:
    path: "{{ cloudflared_config_file_target_path | win_dirname }}"
    state: directory

- name: configuring config windows | Copy config file
  become: "{{ cloudflared_config_file_become }}"
  ansible.windows.win_copy:
    src: "{{ cloudflared_config_file_source_copy_file }}"
    dest: "{{ cloudflared_config_file_target_path }}"
  register: cloudflared_result_config_file_copy
  when: cloudflared_config_file_source_mode == "copy"

- name: configuring config windows | Render config file from template
  become: "{{ cloudflared_config_file_become }}"
  ansible.windows.win_template:
    src: "{{ cloudflared_config_file_source_template_file }}"
    dest: "{{ cloudflared_config_file_target_path }}"
  register: cloudflared_result_config_file_template
  when: cloudflared_config_file_source_mode == "template"

- name: configuring config windows | Write config file from vars mapping
  become: "{{ cloudflared_config_file_become }}"
  ansible.windows.win_copy:
    dest: "{{ cloudflared_config_file_target_path }}"
    content: >-
      {{
        cloudflared_config_file_source_vars_content
        | to_nice_yaml(indent=2, sort_keys=false)
      }}
  register: cloudflared_result_config_file_vars
  when: cloudflared_config_file_source_mode == "vars"
