---
- name: configuring credentials docker | Ensure credentials file parent directory exists
  become: "{{ cloudflared_credentials_file_become }}"
  ansible.builtin.file:
    path: "{{ cloudflared_credentials_file_target_path | dirname }}"
    state: directory
    mode: "0755"

- name: configuring credentials docker | Create temporary credentials file
  ansible.builtin.tempfile:
    state: file
    suffix: ".cloudflared-credentials"
  register: cloudflared_result_credentials_file_tempfile

- name: configuring credentials docker | Copy credentials file to temporary file
  ansible.builtin.copy:
    src: "{{ cloudflared_credentials_file_source_copy_file }}"
    dest: "{{ cloudflared_result_credentials_file_tempfile.path }}"
    mode: "0600"
  register: cloudflared_result_credentials_file_copy
  when: cloudflared_credentials_file_source_mode == "copy"

- name: configuring credentials docker | Write credentials file from vars mapping to temporary file
  ansible.builtin.copy:
    dest: "{{ cloudflared_result_credentials_file_tempfile.path }}"
    content: >-
      {{
        cloudflared_credentials_file_source_vars_content
        | to_nice_json(indent=2, sort_keys=false)
      }}
    mode: "0600"
  register: cloudflared_result_credentials_file_vars
  when: cloudflared_credentials_file_source_mode == "vars"

- name: configuring credentials docker | Write credentials file from token to temporary file
  vars:
    _token_json: >-
      {{
        {}
        if cloudflared_credentials_file_source_token | default('') | trim | length == 0
        else (
          cloudflared_credentials_file_source_token
          | b64decode
          | from_json
        )
      }}
  ansible.builtin.copy:
    dest: "{{ cloudflared_result_credentials_file_tempfile.path }}"
    content: >-
      {{
        {
          'AccountTag': _token_json['a'] | default(''),
          'TunnelID': _token_json['t'] | default(''),
          'TunnelSecret': _token_json['s'] | default('')
        }
        | to_nice_json(indent=2, sort_keys=false)
      }}
    mode: "0600"
  register: cloudflared_result_credentials_file_token
  when: cloudflared_credentials_file_source_mode == "token"

- name: configuring credentials docker | Flush temporary credentials into target file
  become: "{{ cloudflared_credentials_file_become }}"
  ansible.builtin.shell: >
    cat "{{ cloudflared_result_credentials_file_tempfile.path }}" > "{{ cloudflared_credentials_file_target_path }}"
  register: cloudflared_result_credentials_file_flush
  changed_when: true

- name: configuring credentials docker | Remove temporary credentials file
  ansible.builtin.file:
    path: "{{ cloudflared_result_credentials_file_tempfile.path }}"
    state: absent
