---
- name: configuring | Run credentials workflow
  ansible.builtin.include_tasks: configuring_credentials.yml
  when: cloudflared_credentials_file_target_path | trim | length > 0

- name: configuring | Run config workflow
  ansible.builtin.include_tasks: configuring_config.yml
  when: cloudflared_config_file_target_path | trim | length > 0
