---
- name: configuring credentials openwrt | Ensure credentials file parent directory exists
  community.openwrt.file:
    path: "{{ cloudflared_credentials_file_target_path | dirname }}"
    state: directory
    mode: "0755"

- name: configuring credentials openwrt | Copy credentials file
  community.openwrt.copy:
    src: "{{ cloudflared_credentials_file_source_copy_file }}"
    dest: "{{ cloudflared_credentials_file_target_path }}"
  register: cloudflared_result_credentials_file_copy
  when: cloudflared_credentials_file_source_mode == "copy"

- name: configuring credentials openwrt | Write credentials file from vars mapping
  community.openwrt.copy:
    dest: "{{ cloudflared_credentials_file_target_path }}"
    content: >-
      {{
        cloudflared_credentials_file_source_vars_content
        | to_nice_json(indent=2, sort_keys=false)
      }}
  register: cloudflared_result_credentials_file_vars
  when: cloudflared_credentials_file_source_mode == "vars"

- name: configuring credentials openwrt | Write credentials file from token
  vars:
    _token_json: >-
      {{
        {}
        if cloudflared_credentials_file_source_token | default('') | trim | length == 0
        else (
          cloudflared_credentials_file_source_token
          | b64decode
          | from_json
        )
      }}
  community.openwrt.copy:
    dest: "{{ cloudflared_credentials_file_target_path }}"
    content: >-
      {{
        {
          'AccountTag': _token_json['a'] | default(''),
          'TunnelID': _token_json['t'] | default(''),
          'TunnelSecret': _token_json['s'] | default('')
        }
        | to_nice_json(indent=2, sort_keys=false)
      }}
  register: cloudflared_result_credentials_file_token
  when: cloudflared_credentials_file_source_mode == "token"
