---
- name: configuring credentials | Derive configuring host type
  ansible.builtin.set_fact:
    cloudflared_facts_credentials_host_type: >-
      {{
        'docker'
        if cloudflared_installation_mode == 'docker'
        else 'windows'
        if ansible_facts["os_family"] == "Windows"
        else 'openwrt'
        if ansible_facts["os_family"] == "OpenWrt"
        else 'unix'
      }}

- name: configuring credentials | Route credentials file handling by host type
  ansible.builtin.include_tasks: "configuring_credentials_{{ cloudflared_facts_credentials_host_type }}.yml"
