---
- when: ansible_facts["service_mgr"] == "systemd"
  block:
  - name: controlling service linux | Resolve cloudflared binary path
    ansible.builtin.command:
      argv:
        - which
        - cloudflared
    register: cloudflared_result_service_binary_path
    changed_when: false

  - name: controlling service linux | Facted native binary path
    ansible.builtin.set_fact:
      cloudflared_facts_service_binary_path: "{{ cloudflared_result_service_binary_path.stdout }}"

  - name: controlling service linux | Install cloudflared systemd unit
    become: true
    ansible.builtin.template:
      src: cloudflared.service.j2
      dest: "{{ cloudflared_linux_service_unit_path }}"
      mode: "0644"
    register: cloudflared_result_service_systemd_unit

  - name: controlling service linux | Reload systemd daemon when unit changes
    become: true
    ansible.builtin.systemd:
      daemon_reload: true
    when: cloudflared_result_service_systemd_unit.changed

  - name: controlling service linux | Set service enablement
    become: true
    ansible.builtin.systemd:
      name: "{{ cloudflared_service_name }}"
      enabled: "{{ cloudflared_service_enabled }}"

  - name: controlling service linux | Enforce service runtime state
    become: true
    ansible.builtin.systemd:
      name: "{{ cloudflared_service_name }}"
      state: >-
        {{
          'started'
          if cloudflared_service_state == 'started'
          else 'stopped'
          if cloudflared_service_state == 'stopped'
          else 'restarted'
          if cloudflared_service_state == 'restarted'
          else 'reloaded'
        }}
