---
# OS-specific installation tasks should be included from this stage file.
- name: installing | Run Debian installation tasks
  ansible.builtin.include_tasks: installing_debian.yml
  when: ansible_facts["os_family"] == "Debian"

- name: installing | Run Red Hat compatible installation tasks for RedHat and Rocky families
  ansible.builtin.include_tasks: installing_redhat.yml
  when: >-
    ansible_facts["os_family"] == "RedHat" or
    ansible_facts["os_family"] == "Rocky"

- name: installing | Run macOS installation tasks
  ansible.builtin.include_tasks: installing_macos.yml
  when: ansible_facts["os_family"] == "Darwin"
