---
- name: Cleanup | localhost
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Remove image
      community.docker.docker_image_remove:
        name: "{{ item }}"
        force: true
      loop:
        - cloudflare/cloudflared:latest
        - cloudflare/cloudflared:2026.2.0

    - name: Delete tunnel
      ansible.builtin.command:
        argv:
          - >-
            {{
              lookup('env', 'HOME')
              | default('/home/nonroot', true)
              ~ '/.cloudflared/cloudflared'
            }}
          - tunnel
          - delete
          - -f
          - >-
            {{
              lookup('env', 'CLOUDFLARE_TUNNEL_NAME')
              | default('ansible-role-cloudflare-configured-test-tunnel', true)
            }}
      failed_when: false

    - name: Delete local credentials file
      ansible.builtin.file:
        path: >-
          {{
            lookup('env', 'HOME')
            | default('/home/nonroot', true)
            ~ '/.cloudflared/' ~ item
          }}
        state: absent
      loop:
        - >-
          {{
            lookup('env', 'CLOUDFLARE_TUNNEL_NAME')
            | default('ansible-role-cloudflare-configured-test-tunnel', true)
          }}
          ~ '.json'

    - name: Delete local bin file
      ansible.builtin.file:
        path: >-
          {{
            lookup('env', 'HOME')
            | default('/home/nonroot', true)
            ~ '/.cloudflared/cloudflared'
          }}
        state: absent
