---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check package version
      ansible.builtin.command:
        cmd: cloudflared --version
      register: cloudflared_check

    - name: Assert package version
      ansible.builtin.assert:
        that:
          - cloudflared_check.rc == 0
          - cloudflared_check.stdout is defined
          - cloudflared_check.stdout != ''
