---
- name: Converge | tunnel token
  hosts: different
  gather_facts: false
  roles:
    - role: codex_with_openspec.cloudflare_configured
      vars:
        cloudflared_package_version: any
  tasks:
    - name: tunnel token | inspect tunnel credentials file
      ansible.builtin.stat:
        path: >-
          {{
            lookup('env', 'HOME')
            | default('/home/nonroot', true)
            ~ '/.cloudflared/'
            ~ inventory_hostname
            ~ '/'
            ~ lookup('env', 'CLOUDFLARE_TUNNEL_NAME')
              | default('ansible-role-cloudflare-configured-test-tunnel', true)
            ~ '.json'
          }}
      delegate_to: localhost
      register: cloudflared_result_credentials_file_stat

    - name: tunnel token | assert
      ansible.builtin.assert:
        that:
          - cloudflared_result_credentials_file_stat.stat.exists
          # configuring tunnel
          - >-
            cloudflared_facts_account_cert_file ==
            (
              lookup('env', 'HOME') | default('/home/nonroot', true)
            ) ~ '/.cloudflared/cert.pem'

          - >-
            cloudflared_facts_tunnel_name ==
            (
              lookup('env', 'CLOUDFLARE_TUNNEL_NAME')
              | default('ansible-role-cloudflare-configured-test-tunnel', true)
            )
          - >-
            cloudflared_facts_tunnel_credentials_file ==
            (
              lookup('env', 'HOME')
              | default('/home/nonroot', true)
              ~ '/.cloudflared/'
              ~ inventory_hostname
              ~ '/'
              ~ lookup('env', 'CLOUDFLARE_TUNNEL_NAME')
                | default('ansible-role-cloudflare-configured-test-tunnel', true)
              ~ '.json'
            )
          - hostvars['localhost'].cloudflared_facts_unique_tunnels[0].account_cert_file is defined
          - hostvars['localhost'].cloudflared_facts_unique_tunnels[0].tunnel_name is defined
          - hostvars['localhost'].cloudflared_facts_unique_tunnels[0].tunnel_credentials_file is defined
          - hostvars['localhost'].cloudflared_facts_unique_tunnels[1].account_cert_file is defined
          - hostvars['localhost'].cloudflared_facts_unique_tunnels[1].tunnel_name is defined
          - hostvars['localhost'].cloudflared_facts_unique_tunnels[1].tunnel_credentials_file is defined
          # configuring tunnel install
          - cloudflared_result_tunnel_controller_version is not skipped
          - cloudflared_result_tunnel_controller_download_dir is skipped
          - hostvars['localhost'].cloudflared_facts_tunnel_controller_binary_path is not defined
          - hostvars['localhost'].cloudflared_facts_tunnel_controller_release_url is not defined
          - hostvars['localhost'].cloudflared_facts_tunnel_controller_download_filename is not defined
          - hostvars['localhost'].cloudflared_facts_tunnel_controller_extracted_binary_path is not defined
          # configuring tunnel create
            # The item fact within the loop is temporary;
            # the final result is the value of the last item.
          - cloudflared_item_result_tunnel_account_cert_stat is defined
          - cloudflared_item_result_tunnel_list_command is not skipped
          - hostvars['localhost'].cloudflared_item_facts_tunnel_exists == true
            # command tunnel token
          - hostvars['localhost'].cloudflared_item_facts_tunnel_token_argv is defined
          - cloudflared_item_result_tunnel_token_command is not skipped
          - cloudflared_item_result_tunnel_token_credentials_file is not skipped
          - hostvars['localhost'].cloudflared_item_facts_tunnel_token_result is defined
            # command tunnel create
          - hostvars['localhost'].cloudflared_item_facts_tunnel_create_argv is not defined
          - cloudflared_item_result_tunnel_create_command is skipped
          - hostvars['localhost'].cloudflared_item_facts_tunnel_create_result is not defined
          # Although the value of `cloudflared_tunnel_credentials_file` differs for each host,
          # they will ultimately be merged using `cloudflared_tunnel_name`.
          - hostvars['localhost'].cloudflared_facts_tunnel_results | length == 1
      run_once: true
