---
- name: Converge | credentials from token
  hosts: adebian13ll
  gather_facts: false
  roles:
    - role: codex_with_openspec.cloudflare_configured
      vars:
        cloudflared_credentials_file_target_path: /tmp/cloudflare_configured/cloudflared-token.json
        cloudflared_credentials_file_source_mode: token
        cloudflared_credentials_file_source_token: ewogICJhIjogInRlc3QtYWNjb3VudDMiLAogICJ0IjogInRlc3QtaWQzIiwKICAicyI6ICJ0ZXN0LXNlY3JldDMiCn0=

        cloudflared_config_file_target_path: /tmp/cloudflare_configured/cloudflared-vars.yml
        cloudflared_config_file_become: false
        cloudflared_config_file_source_mode: vars
        cloudflared_config_file_source_vars_content: {}
  tasks:
    - name: token | assert
      ansible.builtin.assert:
        that:
          - cloudflared_result_credentials_file_copy is skipped
          - cloudflared_result_credentials_file_vars is skipped
          - cloudflared_result_credentials_file_token is not skipped

    - name: token | inspect credentials file
      ansible.builtin.stat:
        path: /tmp/cloudflare_configured/cloudflared-token.json
      register: cloudflared_result_credentials_file_target_stat

    - name: token | read credentials file
      ansible.builtin.slurp:
        src: /tmp/cloudflare_configured/cloudflared-token.json
      register: cloudflared_result_credentials_file_target_content

    - name: token | assert
      ansible.builtin.assert:
        that:
          - cloudflared_result_credentials_file_target_stat.stat.exists
          - >-
            (
              cloudflared_result_credentials_file_target_content.content
              | b64decode
              | from_json
            )
            ==
            {
              "AccountTag": "test-account3",
              "TunnelID": "test-id3",
              "TunnelSecret": "test-secret3"
            }
