---
- name: Converge | credentials from copy
  hosts: all
  gather_facts: false
  roles:
    - role: codex_with_openspec.cloudflare_configured
      vars:
        cloudflared_credentials_file_target_path: /tmp/cloudflare_configured/cloudflared-copy.json
        cloudflared_credentials_file_source_mode: copy
        cloudflared_credentials_file_source_copy_file: "{{ playbook_dir }}/credentials/credentials.json"

        cloudflared_config_file_target_path: /tmp/cloudflare_configured/cloudflared-vars.yml
        cloudflared_config_file_become: false
        cloudflared_config_file_source_mode: vars
        cloudflared_config_file_source_vars_content: {}
  tasks:
    - name: copy | assert
      ansible.builtin.assert:
        that:
          - cloudflared_result_credentials_file_copy is not skipped
          - cloudflared_result_credentials_file_vars is skipped
          - cloudflared_result_credentials_file_token is skipped

    - name: copy | inspect credentials file
      ansible.builtin.stat:
        path: /tmp/cloudflare_configured/cloudflared-copy.json
      register: cloudflared_result_credentials_file_target_stat

    - name: copy | read credentials file
      ansible.builtin.slurp:
        src: /tmp/cloudflare_configured/cloudflared-copy.json
      register: cloudflared_result_credentials_file_target_content

    - name: copy | assert
      ansible.builtin.assert:
        that:
          - cloudflared_result_credentials_file_target_stat.stat.exists
          - >-
            (
              cloudflared_result_credentials_file_target_content.content
              | b64decode
              | from_json
            )
            ==
            {
              'AccountTag': 'test-account2',
              'TunnelID': 'test-id2',
              'TunnelSecret': 'test-secret2'
            }
